version: "3"
services:
  db:
    image: mysql:5.7.37-oracle
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data:/docker-entrypoint-initdb.d/:rw
      - ./backup:/var/lib/mysql
  backend:
    build: . #lavagna_stable:latest
    container_name: backend
    links:
      - db
    environment:
      DB_DIALECT: MYSQL
      DB_URL: jdbc:mysql://db:3306/lavagna
      DB_USER: root
      DB_PASS: root
      SPRING_PROFILE: dev
  reverse_proxy:
    build: ./nginx
    container_name: r_proxy
    ports:
      - "80:80"
    links:
      - backend
  doc:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: docamentaion
    ports:
      - "8081:8081"

#  proxy:
#    image: baruch_foodtruck
      # context: foodtrucks/project/flask-app/.
      # dockerfile: Dockerfile.nginx
#    ports:
#      - "80:80"
 #   links:
 #     - backend
