FROM maven:3.8.5-openjdk-8 AS build
WORKDIR /app
COPY project .
RUN mvn clean stampo:build

FROM nginx:alpine
COPY --from=build /app/target/lavagna/help /usr/share/nginx/html/static
COPY ./doc/nginx.conf /etc/nginx/nginx.conf
